# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.loglikRE <- function(CovRE, REs, qvec, ni) {
    .Call(`_wglmmModularised_loglikRE`, CovRE, REs, qvec, ni)
}

.loglikCond <- function(REs, phi, family, X, y, Z, weights, scale) {
    .Call(`_wglmmModularised_loglikCond`, REs, phi, family, X, y, Z, weights, scale)
}

.loglikTot <- function(REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, scale) {
    .Call(`_wglmmModularised_loglikTot`, REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, scale)
}

.loglikCondImp <- function(REs, phi, family, X, y, Z, weights, weightsImp, scale) {
    .Call(`_wglmmModularised_loglikCondImp`, REs, phi, family, X, y, Z, weights, weightsImp, scale)
}

.loglikREImp <- function(CovRE, REs, qvec, ni, weightsImp) {
    .Call(`_wglmmModularised_loglikREImp`, CovRE, REs, qvec, ni, weightsImp)
}

.loglikTotImp <- function(REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, weightsImp, scale) {
    .Call(`_wglmmModularised_loglikTotImp`, REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, weightsImp, scale)
}

.GradientAll <- function(REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, scale) {
    .Call(`_wglmmModularised_GradientAll`, REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, scale)
}

.GradientBetaImp <- function(REs, phi, family, X, y, Z, weights, weightsImp, scale) {
    .Call(`_wglmmModularised_GradientBetaImp`, REs, phi, family, X, y, Z, weights, weightsImp, scale)
}

.HessianBetaImp <- function(REs, phi, family, X, y, Z, weights, weightsImp, scale) {
    .Call(`_wglmmModularised_HessianBetaImp`, REs, phi, family, X, y, Z, weights, weightsImp, scale)
}

.NewCoefImp <- function(REs, phi, family, X, y, Z, weights, weightsImp, tol, MaxIt, scale) {
    .Call(`_wglmmModularised_NewCoefImp`, REs, phi, family, X, y, Z, weights, weightsImp, tol, MaxIt, scale)
}

.NewCovREImp <- function(REs, qvec, ni, weightsImp) {
    .Call(`_wglmmModularised_NewCovREImp`, REs, qvec, ni, weightsImp)
}

.ImportanceSampling <- function(MI, modus, Chol, phi, family, X, y, Z, CovRE, weights, qvec, ni, scale) {
    .Call(`_wglmmModularised_ImportanceSampling`, MI, modus, Chol, phi, family, X, y, Z, CovRE, weights, qvec, ni, scale)
}

.GenModusNeu <- function(REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, tol, MaxIt, Chol, scale) {
    .Call(`_wglmmModularised_GenModusNeu`, REs, phi, family, X, y, Z, CovRE, weights, qvec, ni, tol, MaxIt, Chol, scale)
}

.wlmm_transform_cpp <- function(phi, transform, X, y, Z, CovRE, weights, qvec, ni, scale, lambda, MI, iter1, iter2, tol1, tol2, trace, nDecrease) {
    .Call(`_wglmmModularised_wlmm_transform_cpp`, phi, transform, X, y, Z, CovRE, weights, qvec, ni, scale, lambda, MI, iter1, iter2, tol1, tol2, trace, nDecrease)
}

